name: Scheduled GitHub Pages Deployment

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at midnight UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  redeploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Trigger GitHub Pages Build
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.repos.requestPagesBuild({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
